export const AIRPORTS = [
  { code: 'BTS', city: 'Bratislava', country: 'Slovakia' },
  { code: 'VIE', city: 'Vienna', country: 'Austria' },
  { code: 'BUD', city: 'Budapest', country: 'Hungary' },
  { code: 'KSC', city: 'Košice', country: 'Slovakia' },
  { code: 'ROM', city: 'Rome', country: 'Italy' },
  { code: 'MIL', city: 'Milan', country: 'Italy' },
  { code: 'BCN', city: 'Barcelona', country: 'Spain' },
  { code: 'VLC', city: 'Valencia', country: 'Spain' },
  { code: 'MAD', city: 'Madrid', country: 'Spain' },
  { code: 'ATH', city: 'Athens', country: 'Greece' },
  { code: 'PAR', city: 'Paris', country: 'France' },
  { code: 'LON', city: 'London', country: 'United Kingdom' },
  { code: 'BER', city: 'Berlin', country: 'Germany' },
  { code: 'MUC', city: 'Munich', country: 'Germany' },
  { code: 'AMS', city: 'Amsterdam', country: 'Netherlands' },
  { code: 'LIS', city: 'Lisbon', country: 'Portugal' },
  { code: 'OPO', city: 'Porto', country: 'Portugal' },
  { code: 'WAW', city: 'Warsaw', country: 'Poland' },
  { code: 'KRK', city: 'Krakow', country: 'Poland' },
  { code: 'PRG', city: 'Prague', country: 'Czechia' },
  { code: 'ZAG', city: 'Zagreb', country: 'Croatia' },
  { code: 'SPU', city: 'Split', country: 'Croatia' },
  { code: 'DBV', city: 'Dubrovnik', country: 'Croatia' },
  { code: 'CPH', city: 'Copenhagen', country: 'Denmark' },
  { code: 'STO', city: 'Stockholm', country: 'Sweden' },
  { code: 'OSL', city: 'Oslo', country: 'Norway' },
  { code: 'HEL', city: 'Helsinki', country: 'Finland' },
  { code: 'DUB', city: 'Dublin', country: 'Ireland' },
  { code: 'BRU', city: 'Brussels', country: 'Belgium' },
  { code: 'ZRH', city: 'Zurich', country: 'Switzerland' },
  { code: 'IST', city: 'Istanbul', country: 'Turkey' },
]
